### ISSUE TITLE
segmentation fault because ifa_addr may be NULL in getifaddrs

### ISSUE THREAD

**Issue by ileht** [postwait/node-ife#4]
ife.list() leads to 'segmentation fault' with OpenVPN and its tunnels.

ife-sockpacket.cc
if_list_ips(...)
...
+++    if(ifa->ifa_addr == NULL) {
+++    } else
    if(ifa->ifa_addr->sa_family == AF_INET6) {

It solved my problem on Linux

**Comment by postwait** [comment]
Maybe turn this into a pull request?

**Comment by ileht** [comment]
- I'm totally new here, but if 'pull request' implies fork, this is not what I want. I'd prefer a change in the main branch, and I don't see any reason against it.  'ifa_addr' MUST be checked if it is NULL, because 'man getifaddrs' tells me that 'The ifa_addr field references either the address of the interface or the link level address of the interface, if one exists, otherwise it is NULL'
- I have tested only Linux version, but I noticed use of 'ifa_addr' in source files for other systems, and I am not interested in finding and installing (and studying) all those systems and testing 'ife' on them, but I think that people who use those systems can add tests for 'NULL' by themselves, and, preferrably, you can do it as you know or remember or understand your code better than anyone (I, really, found this bug with dumb binary dividing code til I localized the eror, because my experience in C (not even C++) ended some twenty years ago). I can formally review code,  but I have no environment for tests other than Linux' tests.
- If 'pull' means that people who are interested in 'ife' will get alerts of some kind - this would be great, I just don't know how it could ever be done.  In fact, it is 'vippy' that failed and forced me into remembering good old C, so 'vippy' users should also be informed somehow if it is possible.

**Comment by postwait** [comment]
Bing new is okay ;-) All help is appreciated.  "Forking" isn't a bad thing on github, it's just part of the work flow.  Simply fork the repo, make the change to your copy, commit it and push it back up to your copy onh github.  Then open a pull request to ask me to incorporate that change upstream into master.  After I've reviewed and ultimately pulled the change back into the main code base, you can continue working on new features or just delete your fork.

**Comment by ileht** [comment]
I did it.  Maybe this issue should be closed now.

**Comment by ileht** [comment]
OpenVPN creates some 'tun' interfaces.
In addition to base tun0 and tun1 interfaces, my 'OpenVPN-up' script adds some subinterfaces.
My script manipulates interfaces via 'ifconfig'.
'ife' is supposed to allow the same functionality - list/add/delete ip addresses on existing interfaces and their subinterfaces.

But ife.list() does not list any of this tun\* intefaces, not even tun0/tun1 - only eth*.

This is not a problem for me as I need 'ife' only for 'vippy', which processes eth*.
Maybe this is another issue or not an issue at all.

Not shown interfaces:

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.0.1  P-t-P:192.168.0.1  Mask:255.255.0.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

tun0:0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.100.1  P-t-P:192.168.100.1  Mask:255.255.255.128
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1

tun0:1    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.99.1  P-t-P:192.168.99.1  Mask:255.255.255.192
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1

tun0:2    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.98.1  P-t-P:192.168.98.1  Mask:255.255.255.192
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1

tun0:3    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.224.1  P-t-P:192.168.224.1  Mask:255.255.224.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1

tun1      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.0.1  P-t-P:192.168.0.1  Mask:255.255.0.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

tun1:0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.100.1  P-t-P:192.168.100.1  Mask:255.255.255.128
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1

tun1:1    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.99.1  P-t-P:192.168.99.1  Mask:255.255.255.192
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1

tun1:2    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.98.1  P-t-P:192.168.98.1  Mask:255.255.255.192
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1

tun1:3    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.224.1  P-t-P:192.168.224.1  Mask:255.255.224.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1

**Comment by ileht** [comment]
Have had a more careful look at the code.
Docmentation should say:
var ifaces = ife.list(); // Lists all the BROADCAST interfaces on the server.

Or else flags should include IFF_POINTOPOINT, not only IFF_BROADCAST.

May be it's a feature, not a bug, and it is the manual that should be corrected.

**Comment by postwait** [comment]
Docs fixed and PR adapted.
